[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
axel = "DJMyW18aG1g48c534cC2VsaQh15pPan2tMBDkhyhQX1M"
transfer_hook = "5s4m6MbjqjhEeFVKwKXMDR2cXWT7crz5AbgtZeLwCbdJ"

[programs.devnet]
axel = "DJMyW18aG1g48c534cC2VsaQh15pPan2tMBDkhyhQX1M"
transfer_hook = "5s4m6MbjqjhEeFVKwKXMDR2cXWT7crz5AbgtZeLwCbdJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 20000

[scripts]
test = "node --import tsx/esm --test tests/**/*.ts"
