import type { Locator, Page } from 'playwright';
import type { Director } from './director';
import type { Wallet } from './wallet';

/*
 * What the video shows, in order, with its captions. Every step waits for what the page shows
 * on its own, so the same storyline records the local stack or a deployed site: the cars and
 * the demo desk's fleet car are found through the app, never by address.
 *
 * Captions must stay true to the product: no users, partners or revenue, and the cluster and the
 * fictional demo data are named on screen. `say` is the same sentence written for the voice.
 */

export interface Story {
  cluster: string;
  wallet: Wallet;
  /** Whether the storyline ends in the console as the platform admin. */
  console: boolean;
}

/** The smallest element in `scope` that contains every one of `texts`. */
function around(scope: Page | Locator, ...texts: (string | RegExp)[]): Locator {
  // A filter's inner locator is matched inside each candidate, so it starts from the page.
  const page = 'mainFrame' in scope ? scope : scope.page();
  let locator = scope.locator('div, section, li, dl');
  for (const text of texts) {
    locator = locator.filter({ has: page.getByText(text, { exact: typeof text === 'string' }) });
  }
  return locator.last();
}

/** A step of the /demo walkthrough, found by its title. */
function demoStep(page: Page, title: string): Locator {
  return page
    .getByRole('listitem')
    .filter({ has: page.getByRole('heading', { name: title, exact: true }) });
}

async function landing(d: Director, { cluster }: Story): Promise<void> {
  const page = d.page;
  await d.goto('/', page.getByText(/^Live from Solana /));

  await d.caption(
    'AXEL: shares of one working taxi in Kazakhstan, with its income paid out on Solana.',
    async () => {
      await d.pause(500);
      await d.moveTo(page.getByRole('heading', { level: 1 }), 1400);
    },
    { say: 'Axel: shares of one working taxi in Kazakhstan, with its income paid out on Solana.' },
  );

  const where = cluster === 'localnet' ? 'a local Solana validator' : `Solana ${cluster}`;
  const disclosure = page.getByText(/demo data, generated by scripts\/seed-devnet/).first();
  await d.caption(
    `This runs on ${where} with a fictional demo fleet. tKZT is a test tenge.`,
    async () => {
      await d.frame(
        around(page, /demo data, generated by scripts\/seed-devnet/, /^How the demo is built/),
      );
      await d.moveTo(disclosure);
    },
    { say: `This runs on ${where}, with a fictional demo fleet and test tenge.` },
  );

  const stats = around(page, 'Cars listed', 'Payout periods');
  await d.caption('Every figure here is read live from the chain.', async () => {
    await d.scrollTo(stats, 900, 380);
    await d.frame(stats);
    await d.moveTo(page.getByText('Shares sold', { exact: true }));
  });

  const fleet = page.locator('#vehicles');
  await d.caption(
    'Each car has its own Token-2022 share mint. The demo fleet has a car in every state.',
    async () => {
      await d.scrollTo(fleet.getByRole('heading', { name: 'The fleet' }), 1400, 96);
      await d.frame(fleet.getByRole('group', { name: 'Filter by status' }));
      await d.moveTo(fleet.getByRole('button', { name: /^On the road/ }));
    },
    {
      say: 'Each car has its own Token twenty twenty-two share mint. The demo fleet has a car in every state.',
    },
  );

  const raising = fleet.locator('a[href*="/assets/"]').filter({ hasText: 'Raising' }).first();
  await d.caption("Let's open the car that is still raising.", async () => {
    await d.scrollTo(raising, 1600, 140);
    await d.frame(raising);
    await d.pause(300);
    await d.follow(
      raising.getByText('Buy shares'),
      page.getByTestId('escrow-balance').getByText(/tKZT$/),
    );
  });
}

async function carPage(d: Director): Promise<void> {
  const page = d.page;
  const panel = page.getByRole('region', { name: 'Buy shares' });
  const escrow = page.getByTestId('escrow-balance');

  await d.caption(
    "Make, model and park come from the mint's on-chain metadata. The photo is illustrative.",
    async () => {
      await d.frame(around(page, /^Raising$/, /Demo Park/));
      await d.moveTo(page.getByText('Illustrative photo'), 1000);
    },
  );

  await d.caption(
    'Shares sold against the raise goal, with the deadline counting down.',
    async () => {
      await d.frame(
        panel.getByText(/shares sold$/),
        panel.getByRole('progressbar'),
        panel.getByText(/^Raise closes /),
      );
      await d.moveTo(panel.getByRole('progressbar'));
    },
  );

  await d.caption(
    "Buyers' money sits in the program's escrow, read live: shares sold times the price.",
    async () => {
      await d.frame(escrow);
      await d.moveTo(escrow.getByText('In escrow now'));
    },
  );

  const timeline = page.getByRole('region', { name: 'Where this car stands' });
  await d.caption(
    'Goal missed, or car not bought in time? Every buyer takes back exactly what they paid.',
    async () => {
      await d.scrollTo(timeline, 1200);
      await d.frame(timeline);
      await d.moveTo(timeline.getByText('Car bought, money released'));
    },
  );

  const demoLink = panel.getByRole('link', { name: 'Get demo access' });
  await d.caption(
    'Buying needs a KYC record. Judges can get a demo one.',
    async () => {
      await d.scrollToTop(1100);
      await d.frame(demoLink);
      await d.pause(400);
      await d.follow(
        demoLink,
        page.getByRole('heading', { name: 'Try the whole cycle in two minutes' }),
      );
    },
    { say: 'Buying needs a K Y C record. Judges can get a demo one.' },
  );
}

async function demoAccess(d: Director, { wallet }: Story): Promise<void> {
  const page = d.page;
  const burner = wallet.label.source.includes('Burner');
  const access = demoStep(page, 'Get demo access');

  await d.caption(
    burner
      ? 'Judges only need a wallet. Here a local burner test wallet stands in for Phantom.'
      : 'Judges only need a wallet, such as Phantom, switched to devnet.',
    async () => {
      await d.frame(around(page, 'Connect a wallet to start', 'What the demo gives your wallet'));
      await d.click(page.getByRole('main').getByRole('button', { name: 'Connect wallet' }));
      // The wallet dialog scrolls the page behind it; the page should stay where it was.
      await page.evaluate('window.scrollTo(0, 0)');
      await d.click(page.getByRole('dialog').getByRole('button', { name: wallet.label }), {
        settle: 0,
      });
      await wallet.approve(d, () => access.waitFor());
    },
  );

  await d.caption(
    'One signed message writes a 29-day demo KYC record and sends 50,000 test tenge.',
    async () => {
      await d.frame(access);
      const sign = access.getByRole('button', { name: 'Sign and get access' });
      // A deployment with Cloudflare Turnstile enables the button once a person passes it.
      await d.cut(() => d.enabled(sign));
      await d.click(sign, { settle: 0 });
      await wallet.approve(d, () => access.getByText(/^Balance: /).waitFor());
      await d.moveTo(access.getByText(/^Balance: /));
    },
    {
      say: 'One signed message writes a 29-day demo K Y C record, and sends fifty thousand test tenge.',
    },
  );
}

async function buy(d: Director, { wallet }: Story): Promise<void> {
  const page = d.page;
  const step = demoStep(page, 'Buy shares in an open raise');
  const panel = page.getByRole('region', { name: 'Buy shares' });
  const buyButton = panel.getByRole('button', { name: 'Buy shares' });
  const escrow = page.getByTestId('escrow-balance');

  await d.caption('The wallet is verified now, so the open raise accepts it.', async () => {
    await d.frame(step);
    await d.follow(step.getByRole('link', { name: 'Open' }).first(), buyButton);
    await d.frame(buyButton);
    await d.moveTo(buyButton);
  });

  const dialog = page.getByRole('dialog', { name: 'Buy shares' });
  await d.caption(
    'Before anything is signed, the dialog explains the escrow and the exact refund rule.',
    async () => {
      await d.click(buyButton, { settle: 600 });
      const safeguards = around(dialog, 'Where your money goes', /^You pay in /);
      await d.scrollIntoView(safeguards);
      await d.frame(safeguards);
      await d.moveTo(dialog.getByText('Where your money goes'));
    },
  );

  const added = dialog.getByText('2 shares were added to your wallet.');
  await d.caption(
    'Two shares: the payment goes into escrow, and the shares are minted to this wallet.',
    async () => {
      await d.type(dialog.getByLabel('Number of shares'), '2');
      await d.frame(around(dialog, 'You pay'));
      await d.pause(900);
      await d.clearFrames();
      await d.click(dialog.getByRole('button', { name: 'Confirm purchase' }), { settle: 0 });
      await wallet.approve(d, () => added.waitFor());
      await d.moveTo(added);
    },
  );

  await d.cut(async () => {
    await page.keyboard.press('Escape');
    await dialog.waitFor({ state: 'hidden' });
    await panel.getByText('Your shares: 2.').waitFor();
    // The balance is read live and lands a moment after the purchase is confirmed.
    await escrow.getByText(/exactly what buyers paid$/).waitFor();
    await d.pause(500);
  });
  await d.caption('The escrow grew by exactly what was paid.', async () => {
    await d.frame(escrow);
    await d.moveTo(escrow.getByText(/exactly what buyers paid$/));
  });
}

async function fleetShares(d: Director): Promise<void> {
  const page = d.page;
  const shares = demoStep(page, 'Receive shares of a car on the road');
  await d.goto('/demo', shares);
  await d.caption(
    "The desk sends 5 shares of a car on the road. The transfer hook checks both wallets' KYC.",
    async () => {
      await d.scrollTo(shares, 1000, 160);
      await d.frame(shares);
      await d.click(shares.getByRole('button', { name: /^Receive \d+ shares$/ }), { settle: 0 });
      await d.cut(() => shares.getByText(/^You hold \d+ shares of /).waitFor());
      await d.moveTo(shares.getByText(/^You hold \d+ shares of /));
    },
    {
      say: "The demo desk sends five shares of a car on the road. The transfer hook checks both wallets' K Y C.",
    },
  );
}

async function payout(d: Director, { wallet }: Story): Promise<void> {
  const page = d.page;
  const simulate = demoStep(page, 'Simulate a month of income');
  const ready = simulate.getByText(/^Ready to claim: \d/);
  await d.caption(
    "Simulate a month: the operator deposits the car's income, co-signed by its oracle.",
    async () => {
      await d.scrollTo(simulate, 1000, 160);
      await d.frame(simulate);
      await d.click(simulate.getByRole('button', { name: 'Simulate a month' }), { settle: 0 });
      await d.cut(() => ready.waitFor());
      // The step grows with its result; the frame follows it.
      await d.clearFrames();
      await d.frame(simulate);
      await d.moveTo(ready);
    },
  );

  const claimAll = page.getByRole('button', { name: 'Claim all' });
  const figures = around(page, 'Shares held', 'Ready to claim');
  const claimable = around(page, 'Ready to claim', 'Exactly what a claim pays now');
  const holdings = page.getByTestId('holdings-table');
  await d.caption(
    "The portfolio reads both positions from Solana, and exactly what a claim pays, with the program's own math.",
    async () => {
      await d.scrollToTop(900);
      await d.follow(page.getByRole('banner').getByRole('link', { name: 'Portfolio' }), claimAll);
      await d.scrollTo(figures, 900);
      await d.frame(holdings);
      await d.moveTo(holdings.getByRole('row').nth(1));
      await d.pause(1800);
      await d.clearFrames();
      await d.frame(claimable);
      await d.moveTo(claimable);
    },
  );

  await d.caption(
    "Claim: the program pays this wallet's part into its own tKZT account.",
    async () => {
      await d.click(claimAll, { settle: 0 });
      await wallet.approve(d, () => page.getByText(/^Nothing to claim right now\./).waitFor());
      await d.frame(claimable);
      await d.moveTo(claimable);
    },
    { say: "Claim: the program pays this wallet's part into its own test tenge account." },
  );
}

async function verify(d: Director): Promise<void> {
  const page = d.page;
  const check = demoStep(page, "Check the car's data yourself");
  await d.goto('/demo', check);
  const section = page.getByRole('region', { name: "Check the car's data yourself" });
  const verifyButton = section.getByRole('button', { name: 'Verify in this browser' });

  await d.caption(
    "Solana keeps only fingerprints: a hash chain of daily trip data, and each report's hash.",
    async () => {
      await d.scrollTo(check, 1000, 160);
      await d.follow(check.getByRole('link', { name: /^Check / }), verifyButton);
      await d.scrollTo(section, 900);
      await d.frame(around(section, 'Trip days on-chain', 'Attested reports'));
      await d.moveTo(section.getByText('Chain head'));
    },
  );

  const verified = section.getByText('Trip data verified', { exact: true });
  await d.caption(
    'The browser recomputes every hash and rebuilds the exact chain head Solana holds.',
    async () => {
      await d.click(verifyButton, { settle: 0 });
      await d.cut(() => verified.waitFor());
      await d.frame(around(section, 'Trip data verified', /^Your browser rebuilt the chain/));
      await d.moveTo(verified);
    },
  );

  await d.caption(
    'Each income report matches its on-chain hash. The simulated month is labelled as such.',
    async () => {
      await d.scrollTo(section.getByText('Income deposits', { exact: true }), 1400, 140);
      await d.frame(around(section, 'Income deposits', 'Simulated demo month'));
      await d.moveTo(section.getByText('Simulated demo month', { exact: true }));
    },
  );
}

async function solvency(d: Director): Promise<void> {
  const page = d.page;
  const verdict = page.getByText(/pass(es)? every check$/);
  await d.caption(
    'Proof of solvency: every vault checked live against what the program owes holders.',
    async () => {
      await d.scrollToTop(900);
      await d.follow(page.getByRole('banner').getByRole('link', { name: 'Solvency' }), verdict);
      await d.frame(around(page, /pass(es)? every check$/, /^The vaults hold at least/));
      await d.moveTo(verdict);
      await d.pause(1400);
      await d.frame(around(page, 'In income vaults', 'In raise escrows'));
      await d.moveTo(page.getByText('Owed to holders now', { exact: true }));
    },
  );
}

async function operatorConsole(d: Director, { wallet }: Story): Promise<void> {
  const page = d.page;
  if (!(await wallet.becomeAdmin(d))) return;
  const release = page.getByText('Release the raise', { exact: true });
  await d.goto('/admin', page.getByText(/^Console · signed in as /));

  // A funded car shows the admin's weightiest controls: the release and the cancel.
  await d.cut(async () => {
    // The select sits inside its label, so its accessible name also holds the selected car.
    const select = page.getByRole('combobox', { name: /^Car\b/ });
    await select.waitFor();
    const values = await select
      .locator('option')
      .evaluateAll((options) => options.map((option) => (option as HTMLOptionElement).value));
    for (const value of values) {
      await select.selectOption(value);
      await d.pause(600);
      if (await release.isVisible()) break;
    }
    await release.waitFor();
    await d.pause(600);
  });

  const releaseStep = around(page, 'Release the raise', 'SHA-256 of the purchase documents');
  await d.caption(
    'The console reads roles from the chain. A funded raise is released only with the hash of the purchase papers.',
    async () => {
      await d.scrollTo(page.getByRole('heading', { name: 'Car status' }), 1200, 140);
      await d.frame(releaseStep);
      await d.moveTo(page.getByText('SHA-256 of the purchase documents'));
    },
  );

  await d.caption(
    "A release pays only the car's operator, minus the raise fee. The program hard-caps every fee.",
    async () => {
      await d.frame(around(page, 'Fee on raises'), around(page, 'Fee on income'));
      await d.moveTo(page.getByText('Fee on raises', { exact: true }));
    },
  );
}

export async function tell(d: Director, story: Story): Promise<void> {
  await landing(d, story);
  await carPage(d);
  await demoAccess(d, story);
  await buy(d, story);
  await fleetShares(d);
  await payout(d, story);
  await verify(d);
  await solvency(d);
  if (story.console) await operatorConsole(d, story);
}
