/**
 * The documents the seed publishes and commits to on-chain: daily telemetry records (their
 * hashes form each car's telemetry chain), monthly P&L reports and sale reports (their
 * hashes are the deposits' `report_hash`), acquisition documents (the activation's
 * `doc_hash`), the recovery case file and the token metadata JSON.
 *
 * Hashes are SHA-256 of the RFC 8785 canonical JSON, so anyone can recompute them from the
 * published files, and the telemetry head from the daily hashes.
 */
import type { Keypair, PublicKey } from "@solana/web3.js";
import { CITIES } from "./catalog";
import { DAY_STATUSES, STATUS_CODE, type MonthReport } from "./economics";
import { isoDate, monthKey } from "./lib/dates";
import { hashJson, sha256, type Json } from "./lib/jcs";
import type { KeyRing } from "./lib/keys";
import { CONFIG, DATA_ORIGIN, DESK, PAYMENT_DECIMALS, RECOVERY_WALLET, kztToBase, type Plan, type ProjectPlan } from "./plan";

export const NOTICE =
  "Fictional devnet demo data generated by scripts/seed-devnet. The cars, parks and investors do not exist, " +
  "and every figure is derived from labeled assumptions; nothing here describes a real vehicle or business.";

export const PAYMENT_SYMBOL = "tKZT";

export const STATUS_DESCRIPTIONS: Record<string, string> = {
  [STATUS_CODE.active]: "active: rented out to a driver",
  [STATUS_CODE.idle]: "idle: no driver",
  [STATUS_CODE.maintenance]: "maintenance: scheduled service",
  [STATUS_CODE.repair]: "repair: off the road after an accident",
};

/** Every key of the demo, derived from the master secret. */
export interface Roles {
  admin: Keypair;
  kyc: Keypair;
  demoKyc: Keypair;
  treasury: Keypair;
  /** Mint authority of tKZT. */
  faucet: Keypair;
  paymentMint: Keypair;
  desk: Keypair;
}

export function rolesOf(keys: KeyRing): Roles {
  return {
    admin: keys.role("admin"),
    kyc: keys.role("kyc"),
    demoKyc: keys.role("demo-kyc"),
    treasury: keys.role("treasury"),
    faucet: keys.role("faucet"),
    paymentMint: keys.role("tkzt-mint"),
    desk: keys.role(DESK),
  };
}

export function investorKey(keys: KeyRing, id: string): Keypair {
  if (id === DESK) {
    return keys.role(DESK);
  }
  return keys.run(id === RECOVERY_WALLET ? RECOVERY_WALLET : `investor:${id}`);
}

export function shareMintKey(keys: KeyRing, project: ProjectPlan): Keypair {
  return keys.run(`share-mint:${project.id}`);
}

/** A platform role by name: "admin", "kyc", "oracle", "operator:<park>", "demo-operator" and so on. */
export function roleKey(keys: KeyRing, role: string): Keypair {
  return keys.role(role);
}

export function hex(bytes: Uint8Array): string {
  return Buffer.from(bytes).toString("hex");
}

/** `sha256(head || date as u32 LE || data_hash)`, the program's telemetry chain step. */
export function nextHead(head: Uint8Array, date: number, dataHash: Uint8Array): Buffer {
  const le = Buffer.alloc(4);
  le.writeUInt32LE(date);
  return sha256(Buffer.concat([head, le, dataHash]));
}

export const EMPTY_HEAD = Buffer.alloc(32);

export interface Doc {
  doc: Json;
  hash: Buffer;
}

function doc(value: Json): Doc {
  return { doc: value, hash: hashJson(value) };
}

export interface DayEntry {
  date: number;
  record: Json;
  dataHash: Buffer;
  head: Buffer;
  trips: number;
  km: number;
  rentPaidKzt: number;
  statusCode: number;
}

export interface ProjectDocs {
  mint: PublicKey;
  days: Map<number, DayEntry>;
  /** Report id ("2026-03" or "2026-06-sale") → report. */
  reports: Map<string, Doc>;
  acquisition?: Doc;
  headByMonth: Map<string, Buffer>;
  finalHead: Buffer;
  uri: string;
  additionalMetadata: Array<{ key: string; value: string }>;
  tokenMetadata: Json;
}

export interface Documents {
  projects: ProjectDocs[];
  recovery: Doc;
}

function carSummary(project: ProjectPlan): Json {
  return {
    name: project.name,
    make: project.model.make,
    model: project.model.model,
    year: project.year,
    city: CITIES[project.city].name,
    class: project.model.carClass,
    park: project.park.name,
    plate_hash: project.plateHash,
  };
}

/** Car values drawn from the assumptions, labeled as such wherever they are published. */
export function carBasis(project: ProjectPlan) {
  return {
    label: "assumption",
    price_kzt: project.economics.priceKzt,
    daily_rent_kzt: project.economics.dailyRentKzt,
    insurance_kzt_per_year: project.economics.insuranceKztPerYear,
    park_fee_bps: project.park.feeBps,
    depreciation_years: project.economics.depreciationYears,
    residual_value_bps: project.economics.residualValueBps,
  };
}

function dayRecord(mint: PublicKey, day: MonthReport["days"][number]): Json {
  return {
    schema: "axel.telemetry.day/v1",
    data_origin: DATA_ORIGIN,
    mint: mint.toBase58(),
    date: isoDate(day.date),
    status: day.status,
    status_code: STATUS_CODE[day.status],
    trips: day.trips,
    km: day.km,
    rent_paid_kzt: day.rentPaidKzt,
  };
}

function monthReport(project: ProjectPlan, mint: PublicKey, report: MonthReport, head: Buffer): Json {
  const count = (status: (typeof DAY_STATUSES)[number]) => report.days.filter((d) => d.status === status).length;
  const deposited = report.distributableKzt > 0;
  return {
    schema: "axel.report.month/v1",
    data_origin: DATA_ORIGIN,
    notice: NOTICE,
    mint: mint.toBase58(),
    car: carSummary(project),
    period: {
      start: isoDate(report.days[0].date),
      end: isoDate(report.days[report.days.length - 1].date),
    },
    operations: {
      days: report.days.length,
      active_days: count("active"),
      idle_days: count("idle"),
      maintenance_days: count("maintenance"),
      repair_days: count("repair"),
      trips: report.days.reduce((sum, d) => sum + d.trips, 0),
      km: report.days.reduce((sum, d) => sum + d.km, 0),
    },
    income_kzt: { rent_collected: report.rentCollectedKzt },
    costs_kzt: {
      park_fee: report.parkFeeKzt,
      maintenance: report.maintenanceKzt,
      insurance: report.insuranceKzt,
      repairs: report.repairsKzt,
      carried_loss: report.carriedLossKzt,
    },
    distributable_kzt: report.distributableKzt,
    loss_carried_forward_kzt: report.lossCarriedForwardKzt,
    deposit: deposited
      ? {
          kind: "regular",
          gross_base_units: kztToBase(report.distributableKzt).toString(),
          currency: PAYMENT_SYMBOL,
          decimals: PAYMENT_DECIMALS,
          platform_fee_bps: CONFIG.revenueFeeBps,
        }
      : null,
    telemetry: {
      first_date: isoDate(report.days[0].date),
      last_date: isoDate(report.days[report.days.length - 1].date),
      days: report.days.length,
      head: hex(head),
    },
    basis: { ...carBasis(project), maintenance_bps: report.maintenanceBps },
  };
}

function saleReport(project: ProjectPlan, mint: PublicKey, head: Buffer): Json {
  const sale = project.sale!;
  return {
    schema: "axel.report.sale/v1",
    data_origin: DATA_ORIGIN,
    notice: NOTICE,
    mint: mint.toBase58(),
    car: carSummary(project),
    sale: {
      date: isoDate(sale.date),
      price_kzt: sale.priceKzt,
      purchase_price_kzt: project.economics.priceKzt,
      months_operated: project.months.length,
      buyer: "fictional",
    },
    deposit: {
      kind: "final",
      gross_base_units: kztToBase(sale.priceKzt).toString(),
      currency: PAYMENT_SYMBOL,
      decimals: PAYMENT_DECIMALS,
      platform_fee_bps: CONFIG.revenueFeeBps,
    },
    telemetry: { last_date: isoDate(sale.date), head: hex(head) },
    basis: carBasis(project),
  };
}

function acquisitionDoc(project: ProjectPlan, mint: PublicKey): Json {
  return {
    schema: "axel.acquisition/v1",
    data_origin: DATA_ORIGIN,
    notice: NOTICE,
    mint: mint.toBase58(),
    car: carSummary(project),
    purchase: {
      date: project.acquisitionDate!,
      price_kzt: project.economics.priceKzt,
      seller: "fictional dealer",
    },
    raise: {
      shares: Number(project.totalShares),
      price_per_share_base_units: project.pricePerShareBase.toString(),
      currency: PAYMENT_SYMBOL,
      decimals: PAYMENT_DECIMALS,
    },
    basis: carBasis(project),
  };
}

function metadataUri(siteUrl: string, mint: PublicKey): string {
  return `${siteUrl.replace(/\/+$/, "")}/demo-data/${mint.toBase58()}/metadata.json`;
}

/** Fields written into the share mint's token metadata. */
export function additionalMetadata(project: ProjectPlan): Array<{ key: string; value: string }> {
  return [
    { key: "make", value: project.model.make },
    { key: "model", value: project.model.model },
    { key: "year", value: String(project.year) },
    { key: "city", value: CITIES[project.city].name },
    { key: "class", value: project.model.carClass },
    { key: "park", value: project.park.name },
    { key: "plate_hash", value: project.plateHash },
    { key: "data_origin", value: DATA_ORIGIN },
  ];
}

function tokenMetadata(project: ProjectPlan, siteUrl: string): Json {
  const base = siteUrl.replace(/\/+$/, "");
  return {
    name: project.name,
    symbol: project.symbol,
    description:
      `One share of a fictional ${project.year} ${project.model.make} ${project.model.model} taxi in ` +
      `${CITIES[project.city].name}, operated by ${project.park.name}. Devnet demo data.`,
    ...(project.model.hasPhoto ? { image: `${base}/images/cars/${project.model.slug}.webp` } : {}),
    external_url: base,
    attributes: additionalMetadata(project).map(({ key, value }) => ({ trait_type: key, value })),
  };
}

export function buildDocuments(plan: Plan, keys: KeyRing, siteUrl: string): Documents {
  const projects = plan.projects.map((project): ProjectDocs => {
    const mint = shareMintKey(keys, project).publicKey;
    const days = new Map<number, DayEntry>();
    const reports = new Map<string, Doc>();
    const headByMonth = new Map<string, Buffer>();
    let head: Buffer = EMPTY_HEAD;
    for (const report of project.months) {
      for (const day of report.days) {
        const record = dayRecord(mint, day);
        const dataHash = hashJson(record);
        head = nextHead(head, day.date, dataHash);
        days.set(day.date, {
          date: day.date,
          record,
          dataHash,
          head,
          trips: day.trips,
          km: day.km,
          rentPaidKzt: day.rentPaidKzt,
          statusCode: STATUS_CODE[day.status],
        });
      }
      const key = monthKey(report.month);
      headByMonth.set(key, head);
      reports.set(key, doc(monthReport(project, mint, report, head)));
    }
    if (project.sale !== undefined) {
      const last = project.months[project.months.length - 1];
      reports.set(`${monthKey(last.month)}-sale`, doc(saleReport(project, mint, head)));
    }
    return {
      mint,
      days,
      reports,
      acquisition: project.acquisitionDate === undefined ? undefined : doc(acquisitionDoc(project, mint)),
      headByMonth,
      finalHead: head,
      uri: metadataUri(siteUrl, mint),
      additionalMetadata: additionalMetadata(project),
      tokenMetadata: tokenMetadata(project, siteUrl),
    };
  });

  const recovery = plan.recovery;
  const recoveryProject = plan.projects[recovery.project];
  return {
    projects,
    recovery: doc({
      schema: "axel.recovery/v1",
      data_origin: DATA_ORIGIN,
      notice: NOTICE,
      case: `DEMO-REC-${recoveryProject.id}`,
      reason: "lost-key",
      mint: projects[recovery.project].mint.toBase58(),
      from_wallet: investorKey(keys, recovery.from).publicKey.toBase58(),
      to_wallet: investorKey(keys, recovery.to).publicKey.toBase58(),
      shares: Number(recovery.shares),
      evidence:
        "Fictional case for the devnet demo. A real case file holds the owner's notarised request and a " +
        "fresh KYC check of the new wallet; only its hash goes on-chain.",
    }),
  };
}

export function telemetryMonthFile(project: ProjectPlan, docs: ProjectDocs, report: MonthReport): Json {
  const first = report.days[0].date;
  const previous = [...docs.days.values()].filter((d) => d.date < first).at(-1);
  return {
    schema: "axel.telemetry.month/v1",
    data_origin: DATA_ORIGIN,
    notice: NOTICE,
    mint: docs.mint.toBase58(),
    car: project.name,
    month: monthKey(report.month),
    chain: "head' = sha256(head || date as u32 little-endian || sha256(JCS(record))), starting from 32 zero bytes",
    status_codes: STATUS_DESCRIPTIONS,
    head_before: hex(previous?.head ?? EMPTY_HEAD),
    head_after: hex(docs.headByMonth.get(monthKey(report.month))!),
    days: report.days.map((day) => {
      const entry = docs.days.get(day.date)!;
      return { record: entry.record, data_hash: hex(entry.dataHash), head: hex(entry.head) };
    }),
  };
}

