import React from 'react';
import { createHash, webcrypto } from 'node:crypto';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe, expect, it } from 'vitest';
import { projectAddress } from '@/lib/solana/pda';
import {
  fixture,
  FixtureConnection,
  fixtureProject,
  key,
} from '@/lib/solana/__tests__/fixtures/chain';
import { patchProgramAccount } from '@/lib/solana/__tests__/fixtures/accountPatch';
import { NotPublishedError, type JsonFetcher } from '@/lib/verify/published';
import type { Digest } from '@/lib/verify/sha256';
import { AppProviders, testWallet } from '@/__tests__/helpers/providers';
import { VerifyData } from '../VerifyData';

const BASE = 'https://data.example/demo-data';
const MINT = fixture.projects.operating.shareMint;
const PROJECT = projectAddress(key(MINT));

/** WebCrypto as Node ships it; the page uses the browser's. */
const digest: Digest = async (data) =>
  new Uint8Array(await webcrypto.subtle.digest('SHA-256', data));

const sha256 = (data: Buffer | string) => createHash('sha256').update(data).digest('hex');

function nextHead(head: string, date: number, dataHash: string): string {
  const day = Buffer.alloc(4);
  day.writeUInt32LE(date);
  return sha256(Buffer.concat([Buffer.from(head, 'hex'), day, Buffer.from(dataHash, 'hex')]));
}

/** Two days of trip data as a publisher writes them, and the chain head they give. */
function publishedDays() {
  const first = { date: '2026-12-01', km: 212, trips: 14 };
  const second = { date: '2026-12-02', km: 180, trips: 11 };
  const firstHash = sha256('{"date":"2026-12-01","km":212,"trips":14}');
  const secondHash = sha256('{"date":"2026-12-02","km":180,"trips":11}');
  const firstHead = nextHead('00'.repeat(32), 20261201, firstHash);
  const head = nextHead(firstHead, 20261202, secondHash);
  const files: Record<string, unknown> = {
    [`${BASE}/${MINT}/index.json`]: {
      mint: MINT,
      data_origin: 'devnet-demo-seed',
      telemetry: { months: [{ month: '2026-12', file: 'telemetry/2026-12.json' }] },
      reports: [],
      acquisition: null,
    },
    [`${BASE}/${MINT}/telemetry/2026-12.json`]: {
      days: [
        { record: first, data_hash: firstHash, head: firstHead },
        { record: second, data_hash: secondHash, head },
      ],
    },
  };
  return { files, head };
}

/** The operating car of the fixture, with a telemetry chain of `count` days ending at `head`. */
async function nodeWithChain(head: string, count: number, lastDate: number) {
  const accounts = await patchProgramAccount('project', PROJECT, (project) => ({
    ...project,
    telemetryHead: [...Buffer.from(head, 'hex')],
    telemetryCount: count,
    lastTelemetryDate: lastDate,
  }));
  return new FixtureConnection(accounts);
}

const fetcherOf =
  (files: Record<string, unknown>): JsonFetcher =>
  async (url) => {
    if (!(url in files)) throw new NotPublishedError(url);
    return JSON.parse(JSON.stringify(files[url]));
  };

async function renderVerify(
  connection: FixtureConnection,
  fetcher: JsonFetcher,
  baseUrl: string | null = BASE,
) {
  const project = await fixtureProject('operating', connection);
  render(
    <AppProviders connection={connection} wallet={testWallet(null)}>
      <VerifyData project={project} baseUrl={baseUrl} digest={digest} fetcher={fetcher} />
    </AppProviders>,
  );
}

const verifyButton = () => screen.getByRole('button', { name: 'Verify in this browser' });

describe('VerifyData', () => {
  it("rebuilds the car's telemetry chain from the published days and matches Solana's head", async () => {
    const { files, head } = publishedDays();
    await renderVerify(await nodeWithChain(head, 2, 20261202), fetcherOf(files));

    expect(screen.getByText('Trip days on-chain').nextSibling).toHaveTextContent('2');
    await userEvent.click(verifyButton());

    expect(await screen.findByText('Trip data verified')).toBeInTheDocument();
    expect(
      screen.getByText(/rebuilt the chain from 2 published days and got exactly the head/),
    ).toBeInTheDocument();
    expect(screen.getByText('Rebuilt here').nextSibling).toHaveTextContent(
      `${head.slice(0, 8)}…${head.slice(-8)}`,
    );
    // The fixture's three deposits predate any trip data and publish no report.
    expect(screen.getAllByText('Before any trip data')).toHaveLength(3);
    expect(screen.getAllByText('Report not published')).toHaveLength(3);
    expect(
      screen.getByText('These records are fictional demo data generated by scripts/seed-devnet.'),
    ).toBeInTheDocument();
  });

  it('names the day whose published figures were changed after the chain recorded them', async () => {
    const { files, head } = publishedDays();
    const month = files[`${BASE}/${MINT}/telemetry/2026-12.json`] as {
      days: { record: { km: number } }[];
    };
    month.days[1].record.km = 1800;
    await renderVerify(await nodeWithChain(head, 2, 20261202), fetcherOf(files));

    await userEvent.click(verifyButton());

    expect(await screen.findByText("The published data doesn't match")).toBeInTheDocument();
    expect(
      screen.getByText(
        "The record for Dec 2, 2026 doesn't hash to the value published with it: it was changed after publishing.",
      ),
    ).toBeInTheDocument();
  });

  it('flags income reports and purchase papers that no longer hash to what the chain holds', async () => {
    const { files, head } = publishedDays();
    const index = files[`${BASE}/${MINT}/index.json`] as Record<string, unknown>;
    index.reports = [{ id: '2026-12', file: 'reports/2026-12.json', period_index: 0 }];
    index.acquisition = { file: 'acquisition.json' };
    files[`${BASE}/${MINT}/reports/2026-12.json`] = { net_kzt: 1 };
    files[`${BASE}/${MINT}/acquisition.json`] = { price_kzt: 1 };
    await renderVerify(await nodeWithChain(head, 2, 20261202), fetcherOf(files));

    await userEvent.click(verifyButton());

    expect(await screen.findByText('Report changed')).toBeInTheDocument();
    expect(screen.getByText("Don't match the recorded hash")).toBeInTheDocument();
  });

  it('cannot finish while the chain has recorded days nobody published', async () => {
    const { files } = publishedDays();
    await renderVerify(await nodeWithChain('ab'.repeat(32), 3, 20261203), fetcherOf(files));

    await userEvent.click(verifyButton());

    expect(await screen.findByText("Can't finish the check")).toBeInTheDocument();
    expect(
      screen.getByText(/Solana has recorded 3 days, but only 2 are published/),
    ).toBeInTheDocument();
  });

  it('says where it looked when nothing is published for the car', async () => {
    await renderVerify(new FixtureConnection(), fetcherOf({}));

    await userEvent.click(verifyButton());

    expect(await screen.findByRole('alert')).toHaveTextContent(
      `Nothing is published for this car at ${BASE}/${MINT}/index.json.`,
    );
    expect(screen.getByRole('button', { name: 'Verify again' })).toBeEnabled();
  });

  it('offers no check where the deployment publishes no data', async () => {
    await renderVerify(new FixtureConnection(), fetcherOf({}), null);

    expect(
      screen.getByText(
        'This deployment has no published data source, so there is nothing to check against yet.',
      ),
    ).toBeInTheDocument();
    expect(screen.queryByRole('button')).not.toBeInTheDocument();
  });

  it('has nothing to check for a car with no trip data, deposit or release on-chain yet', async () => {
    const connection = new FixtureConnection();
    const project = await fixtureProject('fundraising', connection);
    render(
      <AppProviders connection={connection} wallet={testWallet(null)}>
        <VerifyData project={project} baseUrl={BASE} digest={digest} fetcher={fetcherOf({})} />
      </AppProviders>,
    );

    expect(screen.getByText(/Nothing to check yet/)).toBeInTheDocument();
    expect(screen.queryByRole('button')).not.toBeInTheDocument();
  });
});
